{
 "title": "Keycloak",
 "description": "Keycloak self-provided metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"keycloak\", area=\"heap\"})/sum(jvm_memory_max_bytes{job=\"keycloak\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"keycloak\", area=\"nonheap\"})/sum(jvm_memory_max_bytes{job=\"keycloak\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Failed Logins in Timeframe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(keycloak_user_events_total{event=\"login\", error!=\"\"}[$__range])) by (realm)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_usage{job=\"keycloak\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Failure Rate in Timeframe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(keycloak_user_events_total{event=\"login\", error!=\"\"}[$__range])) / \nsum(increase(keycloak_user_events_total{event=\"login\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Logins in Timeframe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(keycloak_user_events_total{error=\"\", event=\"login\"}[$__range])) by (realm)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Events in Timeframe",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (event)(increase(keycloak_user_events_total{}[$__range]))> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (event)(increase(keycloak_user_events_total{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT in Timeframe",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_user_events_total{event=\"login\"}[$__range]))> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logins by Client in Timeframe [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_user_events_total{event=\"login\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Logins Per CLIENT in Timeframe",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_user_events_total{event=\"login\", error!=\"\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Logins by Client in Timeframe [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_user_events_total{event=\"login\", error!=\"\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio failed vs successful Logins by Client in Timeframe [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_user_events_total{event=\"login\", error!=\"\"}[5m]))/sum by (client_id) (increase(keycloak_user_events_total{event=\"login\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Login Errors - Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Login Errors in Timeframe",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_user_events_total{event=\"login\", error!=\"\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Errors in Timeframe [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_user_events_total{event=\"login\", error!=\"\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Errors by Client in Timeframe [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_id,error) (increase(keycloak_user_events_total{event=\"login\", error!=\"\"}[5m]))",
     "legendFormat": "{{client_id }} - {{error}}"
    }
   ]
  },
  {
   "title": "Refresh-Tokens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Issued Refresh-Tokens [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum(increase(keycloak_user_events_total{event=\"refresh_token\", error!=\"\"}[5m])) by (error)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(keycloak_user_events_total{event=\"refresh_token\", error=\"\"}[5m]))",
       "legendFormat": "Success"
      }
     ]
    },
    {
     "title": "Token refresh failures in Timerange",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "    sum(increase(keycloak_user_events_total{event=\"refresh_token\", error!=\"\"}[$__range]))\n    /\n    sum(increase(keycloak_user_events_total{event=\"refresh_token\"}[$__range]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Issued Refresh-Tokens by Client in Timeframe",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(keycloak_user_events_total{event=\"refresh_token\"}[$__range])) by (client_id) >0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Issued Refresh-Tokens by Client [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 67 },
     "targets": [
      {
       "expr": "sum(increase(keycloak_user_events_total{event=\"refresh_token\"}[5m])) by (client_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Refresh-Tokens by Client in Timeframe",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(keycloak_user_events_total{event=\"refresh_token\", error!=\"\"}[$__range])) by (client_id) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Issued Refresh-Tokens [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 75 },
     "targets": [
      {
       "expr": "sum(increase(keycloak_refresh_tokens_errors_total{}[5m])) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Refresh Token Errors in Timeframe",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(keycloak_user_events_total{event=\"refresh_token\", error!=\"\"}[$__range])) by (error) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Refresh Token Errors [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 83 },
     "targets": [
      {
       "expr": "sum(increase(keycloak_user_events_total{event=\"refresh_token\", error!=\"\"}[5m])) by (error)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Top Requests in Timeframe",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(increase(http_server_requests_seconds_count{service=\"keycloak\", uri!~\"/(health|metrics).*\"}[$__range])) by (uri) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Endpoint [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 60 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"keycloak\"}[5m])) by (uri,status)",
     "legendFormat": "{{ status }} - {{ uri }}"
    }
   ]
  },
  {
   "title": "Top http status in Timeframe",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, sum(increase(http_server_requests_seconds_count{service=\"keycloak\", uri!~\"/(health|metrics).*\"}[$__range])) by (status) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx and 5xx responses by Status [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 68 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=\"keycloak\",status=~\"4.*|5.*\"}[5m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "4xx and 5xx responses by Endpoint [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=\"keycloak\",status=~\"4.*|5.*\"}[5m])) by (uri,status)",
     "legendFormat": "{{ status }} - {{ uri }}"
    }
   ]
  },
  {
   "title": "404 responses by Endpoint [5m]",
   "type": "timeseries",
   "description": "Shows for which (unknown) URLs 404s were returned\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum by (path) (count_over_time({app=\"ingress-nginx\"} |= \"keycloakx\" | pattern `<remote_addr> - <remote_user> <_> \"<method> <path> <_>\" <status> <bytes_sent> \"<_>\" \"<user_agent>\" <_> <duration> [<service>] [<_>] <_> <_> <_> <_> <_>` | status=`404`[5m])) ",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Success Response time [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 779 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_sum{service=\"keycloak\",status=~\"2.*\"}[5m])) by (uri) / sum(increase(http_server_requests_seconds_count{service=\"keycloak\",status=~\"2.*\"}[5m])) by (uri)",
       "legendFormat": "{{ uri }}"
      }
     ]
    },
    {
     "title": "Average Failure Response time [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 787 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_sum{service=\"keycloak\",status=~\"4.*|5.*\"}[5m])) by (uri) / sum(increase(http_server_requests_seconds_count{service=\"keycloak\",status=~\"4.*|5.*\"}[5m])) by (uri)",
       "legendFormat": "{{ uri }}"
      }
     ]
    }
   ]
  },
  { "title": "Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Threads by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum by (state) (jvm_threads_states_threads{job=\"keycloak\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting threads by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum by (pod,state) (jvm_threads_states_threads{job=\"keycloak\",state=~\"waiting\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum(agroal_active_count{container=\"keycloak\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(agroal_available_count{container=\"keycloak\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(agroal_awaiting_count{container=\"keycloak\"})",
     "legendFormat": "Awaiting"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 110 },
   "options": {
    "content": "# Possible improvements\n\n- Simplify redundant visualizations\n- Integrate custom metrics or \"user interactions\"\n- Allow to jump into a more detailed dashboard per Client-ID via Data-Links. \nIn general splitting between a overview and detailed dashboard makes sense\n"
   }
  }
 ]
}